packaging_format = 2
id = "photoprism"
name = "Photoprism"
description.en = "AI-Powered Photos App for the Decentralized Web"
description.fr = "Gestion de photos en ligne"

version = "2023.07.19~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0-only"
website = "https://photoprism.app"
demo = "https://demo-fr.photoprism.app"
admindoc = "https://docs.photoprism.app/developer-guide/"
userdoc = "https://docs.photoprism.app/user-guide/"
code = "https://github.com/photoprism/photoprism"
fund = "https://www.photoprism.app/membership"

[integration]
yunohost = ">= 11.2.0"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = true
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

    [install.init_main_permission]
    help.en = "If enabled, Photoprism will be accessible by mobile apps and by users without a YunoHost account. This can be changed later in the webadmin."
    help.fr = "Si cette case est cochée, Photoprism sera accessible par des applications mobiles et par les utilisateurs n’ayant pas de compte YunoHost. Vous pourrez changer cela dans la webadmin."
    type = "group"
    default = "visitors"

    [install.password]
    help.en = "Photoprism currently supports only one user : admin. Choose a password here."
    help.fr = "Photoprism ne permet qu'un seul utilisateur pour le moment. Choisissez un mot de passe ici."
    type = "password"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["fr", "en"]
    default = "fr"

[resources]
    [resources.sources]
        [resources.sources.main]
        
        amd64.url = "https://github.com/IndrekHaav/photoprism-builds/releases/download/230719-73fa7bbe8/photoprism.tar.gz"
        amd64.sha256 = "88200d98443cc5cb07de20253b70156e16433ed588499435e4ac4c8cf03923e9"
 
    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    sharing.url = "/s"
    sharing.allowd = "visitors"
    sharing.show_tile = false
    sharing.protected = true


    [resources.ports]
    main.default = 2342

    [resources.apt]
    packages = "ffmpeg, libimage-exiftool-perl, mariadb-server, darktable"

    [resources.database]
    type = "mysql"
